### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by dario-ramos** [lasote/conan-mingw-installer#15]
At the moment, only libstdc++ is offered as an option. This breaks mingw builds which require C++11.
MinGW-w64 has no problems building for C++11 manually, using the  -D_GLIBCXX_USE_CXX11_ABI=1 flag.
So it is possible to build for this libcxx version, it just needs to be integrated.

See https://github.com/bitprim/bitprim-conan-boost for a conan package which reproduces this scenario.

**Comment by lasote** [comment]
I'm ok adding it, but, cannot you compile c++11 code against the libstdc++? It's not enough to enable it with `-std=c++11`

**Comment by dario-ramos** [comment]
Sure, we can; the problem is that when the ConanMultiPackager class uploads
the package to Bintray, it always does it with libstdc++. This yields the
wrong hash and when building a package that uses it, it doesn't find the
binary and has to build from source.
