### ISSUE TITLE
Put MSYS tools in path. 

### ISSUE THREAD

**Issue by lasote** [lasote/conan-mingw-installer#2]
The official installer has it in C:\MinGW\msys\1.0\bin
Those tools include make and others.

**Comment by danimtb** [comment]
The mingw installer downloaded with this package does not include msys-tools inside, so thes is no possibility to just include them on the path. We have to download them apart.

Moreover, there is not an unified installer for msys tools and those tools are normally installed apart as "msys-base" which retrieves the files (msys-make, msys-core, msys-bash...): https://sourceforge.net/projects/mingw/files/MSYS/Base/

I think the best approach would be to create another package just for the msys tools that includes the download links for each tool and the include them in the path variable.

**Comment by ericLemanissier** [comment]
isn't it what https://github.com/bincrafters/conan-msys2_installer is for ?

**Comment by danimtb** [comment]
I thought msys2 was a different toolset for mingw, but I can see the same utilities.

msys2_installer provides both the mingw compiler as well as those tools thanks to the msys2-base installer, so it could be a better approach.

I will try it with a consumer for conan to check it works.
Thanks @ericLemanissier!
