### ISSUE TITLE
Problem with gcc path when working in a shell

### ISSUE THREAD

**Issue by osechet** [lasote/conan-mingw-installer#4]
After activating the environment, the `CC` variable contains the full path to gcc using the Windows format:
`CC=e:\.conan\data\mingw_installer\...\bin\gcc.exe`

I have a build that calls gcc in a msys 'sh' shell. The makefile uses the `CC` variable and it leads to errors because the backslashes of the variable are interpreted. I get the following error:
`/bin/sh: e:.conandatamingw_installer...bingcc.exe: command not found`

Since the gcc directory is added to the path, is it really needed to use the full path of gcc for `CC`?

**Comment by lasote** [comment]
The CC variable is used by CMake (and autotools etc) to locate the compiler to be used.
It's very useful if you have a "global" mingw installation in path, it indicates the compiler to choose.
We could try to construct the path with "/" instead of "\", I think it could work in a regular cmd console too but we have to try it.

**Comment by lasote** [comment]
I've opened a PR in the main conan repository to generate the routes with "/" instead of "\" it works too in a regular console so I think it is the more convenient fix.

https://github.com/conan-io/conan/pull/623

**Comment by osechet** [comment]
> The CC variable is used by CMake (and autotools etc) to locate the compiler to be used.

Yes, but if I'm not mistaken, you can just set it to `gcc` and those tools will look for it in the `PATH`.

> We could try to construct the path with "/" instead of "\"

If it works it's fine for me and it should not create compatibility issues.
