### ISSUE TITLE
usage of settings instead of options

### ISSUE THREAD

**Issue by ericLemanissier** [lasote/conan-mingw-installer#8]
In the current version of mingw_installer, compiler version, threads, and exception handling are options. It makes it hard to inter-operate with other conan recipes, where these are settings, because the user has to define twice each of these parameters.
What is the rationale behind this implementation?
I migrated all these options to settings in my fork https://github.com/ericLemanissier/conan-mingw-installer/commit/40981c59a877b7fdf12fb5eee781a87e9c13b5ad and works properly. I have no idea what adaptation should be made to https://github.com/conan-io/conan-package-tools though.

**Comment by lasote** [comment]
That is a very good question. When I made this recipe the settings for MinGW was still not modeled in the conan settings.yml file. Now I think it makes perfectly sense to manage it with settings. 
Could you open a pull request with your changes?
